### PR TITLE
init with backend for new restaurant

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
In collaboration with @MariagiovannaRotundo this PR contains only the backend and the possible test to add a new restaurant

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

What we need to do

- [X] database API to make a new restaurant
- [X] Waiting UI from @MariagiovannaRotundo

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Maybe @reny77 has some comment to add with the DB interface, at the moment I'm thinking to add a password to the restaurant table, but I'm sure that you have some good comment about it

**Comment by reny77** [comment]
> Maybe @reny77 has some comment to add with the DB interface, at the moment I'm thinking to add a password to the restaurant table, but I'm sure that you have some good comment about it

I think that we don't need a password in restaurant entity, The user must be centralized, so when a user with role operator do login, the system load the related restaurant entity by relation.

**Comment by vincenzopalazzo** [comment]
@reny77 
>I think that we don't need a password in restaurant entity, The user must be centralized, so when a user with role operator do login, the system know that he has a operator role (by query on db and relation), so load the related restaurant entity by relation.

In these cases we could define the use case when we register a new restaurant, how managed the DB insert in this case?

**Comment by vincenzopalazzo** [comment]
Ovveride by https://github.com/GreyTeam2020/GoOutSafe_Primer2020/pull/10, I'm closing it

**Pull request closed without merging**
