### PR TITLE
Added other tests

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

### CODE REVIEW

**Comment by francescofact** [comment]
there is a mismatch naming scheme that i have fixed in my PR, that cause some object problems.
In the Restaurant Obj there is the field "covid_measures", while in the RestaurantForm obj there is "covid_m". This name mismatching case the impossibility to fill in forms automatically passing the object. This is crucial for page that allow the user to Update his data (like My Restaurant Data)

**Comment by vincenzopalazzo** [comment]
Mh thanks for reporting this @francescofact I will take the PR #72 and I will fix it with the correct propriety name.

In this PR Travis fails because I added a new test for `test_delete_user`, it is not implemented yes to server-side.

I will fix PR #72 before the end of the day it is not essentially to review it now

**Comment by francescofact** [comment]
Yes sure, take your time. Nothing is urgent.
Thank you!

**Comment by vincenzopalazzo** [comment]
@vincenzopalazzo refused this PR

**Pull request closed without merging**
